/**
 * Pirate\'s Odyssey - API
 * Swagger for Pirate\'s Odyssey API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemRarity } from './item-rarity';
import { ItemType } from './item-type';
import { EquipmentType } from './equipment-type';


export interface EquipmentResponse { 
    armor?: number;
    equipmentType?: EquipmentType;
    id?: string;
    name?: string | null;
    description?: string | null;
    rarity?: ItemRarity;
    price?: number;
    type?: ItemType;
}
export namespace EquipmentResponse {
}


