/**
 * Pirate\'s Odyssey - API
 * Swagger for Pirate\'s Odyssey API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ItemRarity = 'Poor' | 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary';

export const ItemRarity = {
    Poor: 'Poor' as ItemRarity,
    Common: 'Common' as ItemRarity,
    Uncommon: 'Uncommon' as ItemRarity,
    Rare: 'Rare' as ItemRarity,
    Epic: 'Epic' as ItemRarity,
    Legendary: 'Legendary' as ItemRarity
};

