/**
 * Pirate\'s Odyssey - API
 * Swagger for Pirate\'s Odyssey API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EditShipRequest { 
    id?: string;
    name?: string | null;
    minSeat?: number;
    maxSeat?: number;
    speed?: number;
    health?: number;
}

