/**
 * Pirate\'s Odyssey - API
 * Swagger for Pirate\'s Odyssey API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Stats = 'Strength' | 'Constitution' | 'Dexterity' | 'Speed' | 'Intelligence' | 'Wisdom' | 'Charisma';

export const Stats = {
    Strength: 'Strength' as Stats,
    Constitution: 'Constitution' as Stats,
    Dexterity: 'Dexterity' as Stats,
    Speed: 'Speed' as Stats,
    Intelligence: 'Intelligence' as Stats,
    Wisdom: 'Wisdom' as Stats,
    Charisma: 'Charisma' as Stats
};

